name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      ############ Set Up ############

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: install webkit2gtk (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      ############ Build ############

      - name: Build (non-Windows)
        if: matrix.platform != 'windows-latest'
        run: |
          cd packages/desktop
          go build -o ../../emojazz

      - name: Build (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          cd packages\\desktop
          go build -ldflags="-H windowsgui" -o ..\\..\\emojazz.exe

      ############ Packaging (Linux) ############

      - name: Packaging (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          mkdir emojazz-linux
          mv emojazz emojazz-linux/emojazz
          tar -czf emojazz-linux.tar.gz emojazz-linux
      - name: Upload binaries to release (Linux)
        if: matrix.platform == 'ubuntu-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: emojazz-linux.tar.gz
          tag: release-${{ github.ref }}
          overwrite: true
          body: Executable for Linux

      ############ Packaging (macOS) ############

      - name: Packaging (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          mkdir emojazz-macos
          mv emojazz emojazz-macos/emojazz.app
          zip -r emojazz-macos.zip emojazz-macos

      - name: Upload binaries to release (macOS)
        if: matrix.platform == 'macos-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: emojazz-macos.zip
          tag: release-${{ github.ref }}
          overwrite: true
          body: Executable for macOS

      ############ Packaging (Windows) ############

      - name: Packaging (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          mkdir emojazz
          mv emojazz.exe emojazz-windows\\emojazz.exe
          curl https://github.com/webview/webview/raw/master/dll/x64/WebView2Loader.dll --output emojazz-windows\\WebView2Loader.dll
          curl https://github.com/webview/webview/raw/master/dll/x64/webview.dll --output emojazz-windows\\webview.dll
          tar -cvf emojazz-windows.tar emojazz-windows

      - name: Upload binaries to release (Windows)
        if: matrix.platform == 'windows-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: emojazz-windows.tar
          tag: release-${{ github.ref }}
          overwrite: true
          body: Executable for Windows
